// swift-tools-version: 6.2

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Actomaton-Basic",
    platforms: [
        .macOS("15.4"),
        .iOS("18.4"),
        .watchOS("11.4"),
        .tvOS("18.4")
    ],
    products: [
        .iOSApplication(
            name: "Actomaton-Basic",
            targets: ["AppModule"],
            bundleIdentifier: "com.inamiy.Actomaton-Basic",
            teamIdentifier: "UMBZ5WL247",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Actomaton/Actomaton", "0.9.0"..<"1.0.0"),
        .package(url: "https://github.com/pointfreeco/swift-case-paths", "0.7.0"..<"1.5.0"),
        .package(url: "https://github.com/pointfreeco/swift-custom-dump", "1.0.0"..<"1.3.0"),
        .package(url: "https://github.com/pointfreeco/xctest-dynamic-overlay", "1.0.0"..<"1.2.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Actomaton", package: "actomaton"),
                .product(name: "ActomatonUI", package: "actomaton")
            ],
            path: "."
        )
    ]
)