# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://github.com/actions/runner-images/tree/main/images/macos
name: CI

on:
  push:
    branches:
      - main
      - ci/**
  pull_request:

jobs:
  build-package:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build package
      run: make build-package

  build-SwiftUI-Basic:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build SwiftUI-Basic
      run: make build-SwiftUI-Basic

  build-SwiftUI-Gallery:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build SwiftUI-Gallery
      run: make build-SwiftUI-Gallery

  build-UIKit-Gallery:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build UIKit-Gallery
      run: make build-UIKit-Gallery

  build-Favorite-Sync:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build Favorite-Sync
      run: make build-Favorite-Sync

  build-VideoPlayer:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 26.4
      run: sudo xcode-select -s /Applications/Xcode_26.4.app
    - name: Build VideoPlayer
      run: make build-VideoPlayer
