# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://github.com/actions/virtual-environments/blob/master/images/macos
name: CI

on:
  push:
    branches:
      - main
      - ci/**
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build-SwiftUI-Basic:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build SwiftUI-Basic
      run: make build-SwiftUI-Basic

  build-SwiftUI-Gallery:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build SwiftUI-Gallery
      run: make build-SwiftUI-Gallery

  build-UIKit-Gallery:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build UIKit-Gallery
      run: make build-UIKit-Gallery

  build-Favorite-Sync:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build Favorite-Sync
      run: make build-Favorite-Sync

  build-Favorite-Sync:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build VideoPlayer
      run: make build-VideoPlayer
